### PR TITLE
Pandas lesson: Load calendar dates as datetime

### PR DESCRIPTION
**Pull request by encukou**
I realized the behaviour is different than what I wrote. I papered over it on the lesson, but here's a “more right” way to load `sales.csv`.

Do we want to alert students to the change?

### CODE REVIEW

**Comment by hroncok** [comment]
> Do we want to alert students to the change?

I can mention it in the chat.

**Comment by encukou** [comment]
And does the change look good?

**Comment by hroncok** [comment]
Oh, sorry. I haven't checked the changes in output much, but the change in input indeed looks good.

**Comment by encukou** [comment]
OK, thanks!
Output is mostly different formatting, and a few extra columns because `<= '2016-05'` matches all of May, but not `'2016-05-xx'` strings.

**Pull request merged**
